### ISSUE TITLE
Migration to the new server

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#290]
The current server will expires at the end of month (I can however add one more month if we're not ready). I've already rented a fresh new server since the beginning of this month. I'm almost ready to migrate, still need to work on the cron part.

**What will change:**
* 🆕 New server is entirely deployed using Ansible (I keep this part private)
* 🆕 The GeoKrety services are also deployed using Ansible and is hosted in in it's [own repo](https://github.com/geokrety/geokrety-ansible)
* 🆖 Docker images have been reworked and split in `geokrety/website-legacy-base` and `geokrety/website-legacy`. `base` is still based on `php:apache-5`, the second only add the GK code. So we don't need to rebuild everything on code update.
* 🆕 `geokrety/website-legacy-base` is hosted in it's [own repo](https://github.com/geokrety/geokrety-website-docker-base)
* 🆕 Images are now automatically built and [hosted on docker hub](https://hub.docker.com/u/geokrety) - _however not used on production but rebuilt locally (using Ansible)_
* 🆖 Any change to branches `prod`, `master`, `boly38`, `kumy` will automatically trigger the ansible wrapper to check, rebuild and update **all** instances (note, update will only be triggered if the branch has updates).
* 🆕 cdn branches are now also watched to be rebuilt/updated (currently only `master` and `kumy` branches are activated). Each branches (except prod) has an `aufs` mount permitting to have all files from prod and having local updates - useful for testing uploads or statpics updates

**Preparation:**
* DNS TTL lowered
* Data pretransfered
- [x] Pending PR #291, to split docker images
- [x] Pending PR #291, to fix template cdn url dynamically
- [x] Pending PR #291, to retrieve configurations from environment variable too

**Todo:**
- [x] ❗ Rework `script/cron` image
- [x] ❗ Test pictures upload
- [ ] ❕ Documentation about the new architecture
- [x] ❕ Add @boly38 ssh key (please send it privately)
- [ ] ❕ Monitor services (Need to add necessary things on my Xymon server)

Migration day:
- [x] Change DNS entries to migrate
- [x] Synchronize data one last time
- [x] Import latest database
- [x] Raise TTL after migration

I hope to finish the script image today, and migrate during the week end.

**Comment by kumy** [comment]
Note: https://kumy.staging.geokrety.org/ has already been migrated (except cdn which need to be faked in your `/etc/hosts`)

**Comment by kumy** [comment]
**What will change:**
* 🆕 Tagging on `geokrety/website-legacy` will build and store a docker image using the same tag 
![Screenshot from 2019-04-26 21-33-36](https://user-images.githubusercontent.com/176794/56832108-45011900-686b-11e9-97ba-4f23375419ab.png)

**Comment by kumy** [comment]
Migration done.
