### ISSUE TITLE
new-theme QA : add tracking code label id, and app-version id and enable QA tests

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#540]
in order to implement #473 we need to provide an unique id on action item to helps robot framework scenario
- [x] tracking code form label
- [x] footer app version

and enable qa tests for travis branch name 
- [x] add  `feature/new-theme`  to qaTests stage

**Comment by boly38** [comment]
[job](https://travis-ci.org/geokrety/geokrety-website/builds/599134324?utm_source=github_status&utm_medium=notification)
