### ISSUE TITLE
MIGRATION TO NEW_THEME CHECKLIST

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#618]
This list is the "must have fixed issues" before we can migrate to `new-theme` branch:

## Mandatory:
- [x] #619 User avatar is not good in new-theme
- [x] #615  Migrate waypoints imports to new-theme
- [x] #614 Migrate daily mail cron script
- [x] #629 Display avatar picture in floating popup on "has avatar" icon
- [x] #626 No caption in GK map
- [x] #300 Add ability to publish monitoring metrics
- [x] #616 Migrate yearly badges attribution to new-theme
- [x] #633 Migrate batch GK generator - admin feature
- [x] #691 Tracking code generation does not follow rules
- [x] #692 Some historical Tracking Code start with GK
- [x] #617 Allow users to change their username
- [x] #365 Implement XSRF token in all forms
- [x] #476 Redirect or display useful page on 401, 403 errors
- [x] #701 
- [x] #364 Add a search box in the navbar
- [x] #706
- [x] #707
- [x] #421 Rate limit check_*.php endpoints
- [x] #12
- [x] #761 
- [x] #693 

## Optional for GKv2 migration:
- [x] #624 Migrate altitude profile feature
- [ ] #354 Statistics pages not migrated to new theme 
- [x] #693 Tracking Code may be longer than 6 characters
- [ ] #628 Map of the favorite GKs
- [x] #411 Align state between export_oc and exports
- [x] #86 GDPR: option to remove an account #86
- [ ] #85 GDPR: get all personal data
- [x] #84 GDPR: update 'Terms of service'
- [ ] #593 Altitude and countries must be recomputed on daily imports
- [ ] #362 Social share buttons not implemented on new theme
- [ ] #625 gc.hu waypoint name conflict with GC
- [ ] #350 Menu on mobile

## Migration:
- [x] #754 
- [x] #807 

No issue yet:
- [x] Test a special c:geo build
- [ ] Ask some users for feedback before migration
- [x] Communicate to partners about the change (list?)
- [x] ~Migrate our CI to somewhere else (we ran out of free travis-ci.com credits and our request is ignored be the support)~

**Comment by okainov** [comment]
Are those really "must"? Like GDPR things, well, the current website runs without it, right? Which is probably not good, but you wouldn't make it worse at least. Or allowing to change username - this really doesn't sound like "must"...

**Comment by kumy** [comment]
I agree with you, not all of them are required for the migration.

**Comment by kumy** [comment]
I've splited the list above. But I should keep in mind that when the migration occur, I have to be available for some time as I'm pretty sure there will be some problems arising ;) I hope it will be finally soon!!!

**Comment by kumy** [comment]
The mandatory list is now complete :partying_face:

**Comment by kumy** [comment]
The mandatory list is now complete :partying_face:

I've been working on this for so long! I'm really pleased to be there now :) But the work is not complete.

I think the next website version GKv2 (aka `new-theme`) has now enough core features ready to replace the actual website. Sure there are many missing features but I think it's really usable.

The public staging instance is https://new-theme.staging.geokrety.org/. Database is synchronized from production every days at 2am UTC. So there is no problem if tests are made there.

Bugs should be reported on [GitHub](https://github.com/geokrety/geokrety-website/issues). If possible add label `new-theme`. Translations are hosted on [crowdin](https://crowdin.geokrety.org/).

Regarding the api and legacy urls, I did my best to recreate some legacy endpoints so the migration should be transparent for partners. Partners are however requested to test their product on their staging/development environments with GKv2 using  the url above.

The migration date will be set depending of the quantity, severity and time need to fix the new found bugs. :)

## Known changes list
### Rate limit system
Api endpoint now have 2 types of rates limits:
1. Use nginx rate-limiting and limit the number of request per second per group of endpoints
2. Authenticated endpoints have requests limits calls per days.

For both of them should be quite high. Let me know if some needs tuning. For the 2nd point, for each request you'll find in the header the current consumption, limit and count period.

### GKM/GK fusion
On migration, the api.geokretymap.org will point to api.geokrety.org

- Rate Geokrety
- Races
- Users and GeoKrety statistics
- Create online tutorials, video? (need help)

### Moves support timezones
Historically all date times were processed as if they were UTC. Now timezones should be properly handled. On legacy api endpoints, there is now a new `timezone` parameter (default to `UTC`)

# Next actions

- [ ] Ask some key users for test and feedback before migration
  - @filipsPL 
  - @boly38
  - @okainov 
  - @harrieklomp 
  - @Lineflyer 

- [ ] Check/verify/close the [list known issues](https://github.com/geokrety/geokrety-website/issues?q=is%3Aopen+is%3Aissue+label%3Anew-theme)


- [ ] Communicate to partners about the changes (list above?) 
How should we proceed? Open an issue on each project (where? need list of bug trackers)
This [private discussion](https://github.com/orgs/geokrety/teams/contributors/discussions/5) may need to be updated
  - c:geo
  - opencaching.pl
  - opencaching.de (need contact email)
  - opencaching.nl
  - opencaching.uk (need contact email)
  - opencaching.us (need contact email)
  - gc.su.pl
  - redan.art.pl
  - GeoKrety Toolbox:
    - Firefox: https://raw.githubusercontent.com/geokrety/GeoKrety-Toolbox/master/GeoKrety.Toolbox.user.js
    - Chrome: https://chrome.google.com/webstore/detail/geokrety-toolbox/ldbheajkebdflbjdckojokbfdndkahnl?hl=en-US (@simor ?)
  - GeoKrety Logger https://sourceforge.net/p/geokretylog/code/HEAD/tree/
  - 
  - ???

- [ ]  ???

**Comment by Lineflyer** [comment]
Will test as time permits.

Contact to oc.de could possibly be @teiling88 or he will know the right person I guess.

**Comment by okainov** [comment]
>Api endpoint now have 2 types of rates limits:

So, for dummies, can you make some short "action required" message for geocaching service maintainers?

- Do I need to update API endpoints URLs? Like, `if you're using endpoint X -> you MUST change to Y, otherwise no action required`
- Do I need to update parameters for the query?

So far my understanding is that everything should continue to work as is and no changes should be required from us.

>How should we proceed? Open an issue on each project (where? need list of bug trackers)

I'd say it might be good enough to submit bunch of emails and/or issues directly in GK github mentioning people, if folks are active and they comment/reply - you're ok. If not - you can just close those issues after X months of inactivity (because they would be still off-topic here anyway). This looks easy enough and also relatively good to track the progress

>gc.su.pl

Sounds like something went wrong here =) Did you want to split it to two items?

**Comment by kumy** [comment]
> So far my understanding is that everything should continue to work as is and no changes should be required from us.

Exactly, this is the plan. But would be nice if partners could ensure that everything is all right.

**Comment by andrixnet** [comment]
@bekuno you are correct. Meaning developer contact. 
Thank you for noticing.

**Comment by andrixnet** [comment]
My few bits: 
- intended minimum width: 1600? (it looks to me below this the top menu splits on 2 rows.
- top menu should not overflow on top image/banner when it is shown as 2 rows
- if I read the code correctly, this is based Bootstrap 3, right? I wouldn't jump to 5, but wouldn't hurt to go to 4 (unless current release schedule is too tight).
- footer color scheme is poorly readable.
- maybe something could be done to prevent horizontal scroll in inventory list
- from GDPR point of view I'd host all resources (like libraries) rather then use their CDNs
- the "move GK" icon, though colorful, is hard to understand, compared to the B&W "recently posted moves"
- posted pictures - table contains too small cells thus yielding too little text in too large font. 
- I'm working on some OC geocache icons to be SVG. I'll see if I can make some icons for GK, they seem to be based on the OC treasure chest.
- overall a feeling of a bit more data then the font size can accomodate in an optimal way (note: I'm using large fonts for eyesight saving, if I scale 90% or 80% it looks better, so judge accordingly)
- desktop view too much like mobile portrait layout
- my statpic shows a broken image (account andrixnet). Not sure if an issue.

My appologies, this was a very quick look. I will try to give much more feedback in detail, but this short summary is all I could do on short notice. Will be back. ;-)

**Comment by boly38** [comment]
Hi @kumy ; amazing work you'he done 👏 / I will try to give you some feedback on my free time on [this wiki page](https://github.com/geokrety/geokrety-website/wiki/new-theme---2022-06---Boly38-review---temp-page---wip)
- I write all I have in mind while surfing (that maybe not a good news :p ) / I'll skip good points (but they are numerous!)
- if I find a "medium" Issue, I will create directly a ticket, but not for the rest (minor) 
- if you read me, for each section, you could add a KumyComment if you want: >> Ignored / createAnIssuePlease / okNiceButWontDoIt (and then I could create related minor issue if needed)

**Comment by kumy** [comment]
Thanks for the feedback @boly38, comments added to the wiki page

**Comment by kumy** [comment]
Thanks for your time and help on this subject.

I know there will be lot of design issues (I'm sorry for that), but your first comments are good and very welcome.

Apart from graphic point of view, I'm really interested in real bugs or not handled edge cases. Tests on security side are also very welcome XSS, sql injection, brut force or whatever an evil guy could imagine.

**Comment by kumy** [comment]
Thanks @bekuno, the private contact list has been updated :+1:

**Comment by okainov** [comment]
Any estimate to actually perform the migration? Should be good enough to migrate :)

**Comment by kumy** [comment]
Announcement send via #754 + via mail.

**Comment by kumy** [comment]
> Any estimate to actually perform the migration? Should be good enough to migrate :)

@okainov Let's say 3 - 4 month since now -> Feb/march 2023 :shrug:

**Comment by kumy** [comment]
Sadly I didn't received any confirmation yet from any of the partners tests... :(

**Comment by kumy** [comment]
I think I'm quite ready to switch on GKv2, I wrote #807 with the migration steps.

I'm planning to switch on **January 3, 2023** starting at ~9 am UTC. There will be 2 hours of interruption.

**Comment by kumy** [comment]
GKv2 is out. Closing this one.
